## Refer to Using dbt with Dagster, part one for info about this file:
## https://docs.dagster.io/integrations/dbt/using-dbt-with-dagster/part-one

version: 2

sources:
  - name: reseller_csv
    meta:
      external_location: "read_csv('/shared/csv/DailySales_*.csv', auto_detect=True)"
    tables:
      - name: sales
  - name: reseller_json
    meta:
      external_location: "read_json('/shared/json/rawDailySales_*.json', auto_detect=True, format='array')"
    tables:
      - name: sales
  - name: oltp
    meta:
      external_location: "postgres_scan('postgresql://{{env_var('POSTGRES_USER')}}:{{env_var('POSTGRES_PASSWORD')}}@oltp:5432/sales_oltp','public', '{name}')"
    tables:
      - name: channels
      - name: customers
      - name: products
      - name: resellers
      - name: transactions




